### ISSUE TITLE
Optimizing nPrint reading

### ISSUE THREAD

**Issue by JordanHolland** [nprint/nprintML#39]
Writing each nPrint to disk and reading it in using `pd.read_csv` is clearly our bottleneck at this point. It would be best to brainstorm ways around reading and writing every nPrint twice. Perhaps nPrint's file format itself could be better? Or should we pipe the stdout directly to the python thread rather than writing each nPrint to disk.

**Comment by jesteria** [comment]
I've put some thought into this…

1. At this stage we should be sure we (I) have at least one applicable test set, and collect some useful stats on how our changes affect performance across large and small data sets.
2. Initially I'd thought about investigating how to work with the disk (at a lower level) to try to ensure a more performant read; or, to try to keep all ingested pre-aggregation data in memory/streamed, (_unless_ the user requests to retain these artifacts on disk, in which case we fall back to existing, poor performance). On second thought, I think we can do better than that. For example, we could pipe nPrint processes' outputs into spooled files – like `SpooledTemporaryFile` but not temporary, rather set to the output directory as now – and configured such that small datasets are kept in memory, while retaining much the same interface, yet very large datasets are transparently written eagerly to disk. We'd still likely want to ensure that these artifacts are written to disk, in the end, regardless – and this could create a (small?) additional bottleneck of its own; but, I doubt it, or anyway I think this can be managed, and will be an improvement, (since the _reading_ back from disk is avoided in the problematic case).
3. We could further improve this by indeed streaming these artifacts to the aggregation step as they're produced, (likely in the form of futures objects). (And, IIRC, in aggregation we're currently collecting _all_ individual DataFrames into a list and then concatenating this into a single DataFrame. We could alternatively read the stream directly into a single DataFrame, perhaps, with something like – `pd.concat(pd.read_csv(future_result) for future_result in streamed_files)`.)

**Comment by jesteria** [comment]
4. And, on third thought, we can investigate to what extent the "spooled file" could also, or alternatively, operate like a `tee` – reading nPrint output into memory as it's produced, (assuming nPrint writes lines iteratively in that way), and immediately aggregating each line, as well as writing it to disk in our artifact. This might also cover the case of large data sets, (even though the case of _many_ large data sets might not be a common one). Regardless, it might be a more appropriate model than the "spooled file," which switches based on total file size, or merely a useful extension to it.

**Comment by jesteria** [comment]
Awesome :+1:
